{% set name = "python-magic" %}
{% set version = "0.4.24" %}
{% set hash_val = "de800df9fb50f8ec5974761054a708af6e4246b03b4bdaee993f948947b0ebcf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}
  patches:
    # - discover-libmagic-dylib.patch  # [osx]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - libmagic
    - python

test:
  imports:
    - magic

about:
  home: http://github.com/ahupp/python-magic
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: File type identification using libmagic

extra:
  recipe-maintainers:
    - mariusvniekerk
