travis:
  secure:
    BINSTAR_TOKEN: O8gNom4ARGAdm4clyq8/XwJwRj0Xxv3S2YKL+kyoHbxzeOzd7qhSVrfPXTq+UIoiyze7iLAXRexcP0kCcG/St+ls4oMaCx1s1SN9SDH+qJK0WEBjPZICdKKc/xmSjmHRgh5IESu9AvP3NuJOmkQheqWtp0PkFseiGry5VIsPvB7EqGKMK0B+zfrnVAwbNRjmMfRibpDGutLwzZTP8VYfU0UxjFZbFlVr8sthyvQ3ZzYYD4jktj0iLkfqQyocq5MIq/9Kg2YGrjZSvpCPb+50lEi5SqZ8n4WCYBjJwV5i7i4AN6hOtAFT+VaM37T3G+ckg2DVcb//F4Dx+PV7INbJZXj4ltFoh1c0j4wacCofBIKU9lFAxDrRJPtdYvmEggFrJqUjISErdMZIK4HUFZYV/gsMPjLJAAeDO7GEmrYzyO6qD9TGpUf0rpuXPjbpgDNzasdQYLg8V8Sl2dVo0I546kJ3UZ6DbNvwevlt8iKi0H7hQv720TvvKdhl7XboRK6geVBgGbxxeWYeSCp1wxIRdhaMYJfs/Q7mkGJgI1EHwLc18FCB4VCWvhVpBDlT187BY+yenQCXWsHAd3BFdxLxIafmvQQc5+DRCic7eClDhLiH6iYB2usQkDHWeJkkNzx2O99pdg13At6dpNsYZTLQcXTGhspgNvBJCQy2ivfbjpM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
