travis:
  secure:
    BINSTAR_TOKEN: XB6s5B56HkYV4pbvlBNAFZ2AB3ao4yt4nEG4Lrtg1vRtYrZWFw5aXwkjCD5g90ZKufj+6iiF5TZTEw9A7vevTyY4oN1EWywdjPHdsdZDXEDNrnYANeFJ8zmjAyU0AIXYnFc+ERRfhvTgjClbd0EndAlDANCw+AnVXTn19+f5PU5xDad4vAIx6hUxALE1S/8GzZnnSqNqX8bv0pXucWZDA1LNpnSe2AjmUv3VmjNnhDB+FtDhGvBdFZqc2FU3vp77twq7nNyX24uek81Nh5yrM6qV/FXsYlnL7O0N5WmtjACkfpXdTn08rENfuPIfXAsFVHoXYu0L+3uJtTvo9NuRNqKjLpInI60YU+KPqELwf8rpFH8h5WEbIKOkY6Lwk/C6/XhhCeaw8GnLxH9deNcGvzT/zp1XRlkXVI8//5twYTV0Nzr1g3VOa3s9s2Z8na9W+hjzpUYSbUGSpJyzYZsTFN8l2dFqVBmPub4jNcm/cKeUuXS6s/ZfBzYRWZYeT1768MVJleEKpSqyXfMd0eJ985PbLuKHAGDJ+M5zm6+r71ufir1Zb7ET+6eyka/kfE3em5WUprdqU9JfysXKbwnLekdLtCLxH9+bemNReDIrkpyWxX2fb/Ju7BoHLVw76svENDlBBDFRrpzTT1m0Brmj06/43pfolanIMpPjb0FFaKw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
